### PR TITLE
Zy/42 skip login

### PR DESCRIPTION
**Pull request by zheyxu**
For issue #42

### CODE REVIEW

**Comment by gjwgit** [comment]
Let's rename it to `requireLogin` which is more informative.

**Review by gjwgit — APPROVED** [review]
Looking good. Thanks @zheyxu. I swapped CONTINUE and GET A POD since GET A POD will disappear as a button soon. Please review. Once we have a second approval please merge.

**Comment by gjwgit** [comment]
Awaiting @anushkavidanage or @NinadBhat to approve then @zheyxu to merge.

**Comment by gjwgit** [comment]
Thanks for the merge @zheyxu. I've tested and run `make prep`. All looking good. @NinadBhat or @anushkavidanage can you please review and approve so that @zheyxu can merge this PR. Thanks.

**Review by NinadBhat — APPROVED** [review]

**Pull request merged**
